# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_interface.ui'
#
# Created: Thu Jun 21 14:22:16 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import PyQt4.Qwt5 as Qwt

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1382, 774)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.pota = Qwt.QwtKnob(self.centralwidget)
        self.pota.setObjectName(_fromUtf8("pota"))
        self.verticalLayout_3.addWidget(self.pota)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Vmax_button = QtGui.QPushButton(self.centralwidget)
        self.Vmax_button.setObjectName(_fromUtf8("Vmax_button"))
        self.horizontalLayout_2.addWidget(self.Vmax_button)
        self.Vpp_button = QtGui.QPushButton(self.centralwidget)
        self.Vpp_button.setObjectName(_fromUtf8("Vpp_button"))
        self.horizontalLayout_2.addWidget(self.Vpp_button)
        self.stop_button = QtGui.QPushButton(self.centralwidget)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.input_text = QtGui.QTextBrowser(self.centralwidget)
        self.input_text.setObjectName(_fromUtf8("input_text"))
        self.gridLayout.addWidget(self.input_text, 0, 3, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.plus_button = QtGui.QPushButton(self.centralwidget)
        self.plus_button.setObjectName(_fromUtf8("plus_button"))
        self.verticalLayout_2.addWidget(self.plus_button)
        self.minus_button = QtGui.QPushButton(self.centralwidget)
        self.minus_button.setObjectName(_fromUtf8("minus_button"))
        self.verticalLayout_2.addWidget(self.minus_button)
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.verticalLayout_2.addWidget(self.lcdNumber)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.ecrire_button = QtGui.QPushButton(self.centralwidget)
        self.ecrire_button.setObjectName(_fromUtf8("ecrire_button"))
        self.verticalLayout_5.addWidget(self.ecrire_button)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.nom_registre = QtGui.QLineEdit(self.centralwidget)
        self.nom_registre.setObjectName(_fromUtf8("nom_registre"))
        self.verticalLayout_5.addWidget(self.nom_registre)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.nom_donnee = QtGui.QLineEdit(self.centralwidget)
        self.nom_donnee.setObjectName(_fromUtf8("nom_donnee"))
        self.verticalLayout_5.addWidget(self.nom_donnee)
        self.lire_button = QtGui.QPushButton(self.centralwidget)
        self.lire_button.setObjectName(_fromUtf8("lire_button"))
        self.verticalLayout_5.addWidget(self.lire_button)
        self.res_lect = QtGui.QLineEdit(self.centralwidget)
        self.res_lect.setObjectName(_fromUtf8("res_lect"))
        self.verticalLayout_5.addWidget(self.res_lect)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ANALOG_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.ANALOG_checkbox.setObjectName(_fromUtf8("ANALOG_checkbox"))
        self.gridLayout_2.addWidget(self.ANALOG_checkbox, 2, 0, 1, 1)
        self.SPI_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.SPI_checkbox.setObjectName(_fromUtf8("SPI_checkbox"))
        self.gridLayout_2.addWidget(self.SPI_checkbox, 3, 0, 1, 1)
        self.UART_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.UART_checkbox.setObjectName(_fromUtf8("UART_checkbox"))
        self.gridLayout_2.addWidget(self.UART_checkbox, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1382, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuMenu.addAction(self.actionSettings)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QT interface", None))
        self.label_5.setText(_translate("MainWindow", "           PWM", None))
        self.label_7.setText(_translate("MainWindow", "Période", None))
        self.label_8.setText(_translate("MainWindow", "Rapport cyclique", None))
        self.label_2.setText(_translate("MainWindow", "                                                           Oscilloscope", None))
        self.Vmax_button.setText(_translate("MainWindow", "Vmax", None))
        self.Vpp_button.setText(_translate("MainWindow", "Vpp", None))
        self.stop_button.setText(_translate("MainWindow", "STOP", None))
        self.label.setText(_translate("MainWindow", "    LCD COMMAND", None))
        self.plus_button.setText(_translate("MainWindow", "+", None))
        self.minus_button.setText(_translate("MainWindow", "-", None))
        self.label_3.setText(_translate("MainWindow", "                         I2C", None))
        self.ecrire_button.setText(_translate("MainWindow", "Ecrire", None))
        self.label_4.setText(_translate("MainWindow", "Registre", None))
        self.label_6.setText(_translate("MainWindow", "Donnée", None))
        self.lire_button.setText(_translate("MainWindow", "Lire", None))
        self.ANALOG_checkbox.setText(_translate("MainWindow", "ANALOG", None))
        self.SPI_checkbox.setText(_translate("MainWindow", "SPI", None))
        self.UART_checkbox.setText(_translate("MainWindow", "UART", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
